In [37]:
#call library

import os
import pandas as pd
from sklearn.preprocessing import MinMaxScaler
import numpy as np
import matplotlib.pyplot as plt
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.utils import to_categorical
scaler = MinMaxScaler()

folder_path_growth = "C:/Users/jahye/Desktop/research/growth1"
for filename in os.listdir(folder_path_growth):
    file_path = os.path.join(folder_path_growth, filename)
    if os.path.isfile(file_path):
        with open(file_path, "r") as f:
            print(f)

In [23]:
# set file path
folder_path = 'C:/Users/jahye/Desktop/research/growth2000'

# load file name in folder
file_names = os.listdir(folder_path)
data_array = []
data_list = []

for file in file_names:
    # set file path
    file_path = os.path.join(folder_path, file)
    
    # load csv file as dataframe
    df = pd.read_csv(file_path)

    #preprocessing column
    df = df.drop(['Date','Open','Close'], axis=1)
    df = df.rename(columns={'Adj Close':'Close'})
    df['Diff'] = df['High'] - df['Low']
    df = df.drop(['High','Low'], axis=1)

    #change 0 value to 0.000001
    df = df.replace(0, 0.000001)

    #log transform
    df = np.log(df)

    #using minmaxscaler of each column in df
    df[['Close','Volume','Diff']] = scaler.fit_transform(df[['Close','Volume','Diff']])

    #apply weight
    df['input'] = df['Close'] * 0.4 + df['Diff'] * 0.3 + df['Volume'] * 0.3

    #drop column
    df = df.drop(['Close','Volume','Diff'], axis=1)

    #dataframe to list
    df = df['input'].tolist()

    #insert list to array
    data_array.append(df)
    
    # save dataframe in variable without '.csv' extension
    var_name = file.replace('.csv', '')
    globals()[var_name] = df
    data_list.append(var_name)

In [28]:
arr = np.array(data_array)

C:\Users\jahye\AppData\Local\Temp\ipykernel_17476\3738872752.py:1: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  arr = np.array(data_array)


In [42]:
arr[0]

[0.454395756277025,
 0.7644196468810709,
 0.7201071806709509,
 0.7248097654241366,
 0.7511889058817673,
 0.7550922869749496,
 0.7207159676355337,
 0.7552611089846983,
 0.454395756277025,
 0.740793634872739,
 0.7647849031471327,
 0.7626245591049319,
 0.734601035274356,
 0.7399803161848997,
 0.7548399800404806,
 0.7435617132068189,
 0.7323530940266416,
 0.714981062465856,
 0.6914642024328387,
 0.731814822251079,
 0.7087918716909762,
 0.6984944796463773,
 0.6931816227279494,
 0.6336686971431433,
 0.7292007292150782,
 0.5848622907778468,
 0.6850056974210339,
 0.711103242851884,
 0.6919439190422052,
 0.7359596213868842,
 0.6551064475359479,
 0.70289426658255,
 0.7344881758977768,
 0.7414354398933475,
 0.7274066774325909,
 0.6528914450950726,
 0.707663210653997,
 0.6375825238223638,
 0.7011306608845307,
 0.6369442568591197,
 0.7157133771930327,
 0.6919960930978689,
 0.7047248971238271,
 0.4189555717257972,
 0.6826613845146282,
 0.7338484267555929,
 0.6566062527941876,
 0.7336549582203623,
 0

In [43]:
temp = pad_sequences(arr, dtype='float32')

In [46]:
temp[1]

array([0.        , 0.29526302, 0.3541986 , ..., 0.731694  , 0.75994277,
       0.750091  ], dtype=float32)

In [140]:
len(data_array)

775978

In [126]:
AAPL['input'].tolist()

[0.3451440910166448,
 0.3374972846190637,
 0.3272239354267751,
 0.2928618289145483,
 0.36047959020609366,
 0.24090160092045326,
 0.31784933362342793,
 0.2767772003555766,
 0.25835125421528293,
 0.22081083696019627,
 0.21625389755531652,
 0.22941009756266323,
 0.18405062411661754,
 0.2590965248756981,
 0.20876797403672354,
 0.28966794752615854,
 0.41202080615018133,
 0.2873623035549774,
 0.31864968803306437,
 0.25936124788947196,
 0.24015553946097334,
 0.30032048972980174,
 0.35419240861528994,
 0.36364032982331507,
 0.4004927103072444,
 0.3012709549584779,
 0.42223968189423955,
 0.3352040695159193,
 0.2778646680228983,
 0.24351616807888737,
 0.28604783499039077,
 0.27414537636517955,
 0.21214628470632657,
 0.23813995611306582,
 0.23163813193159102,
 0.2203411994108482,
 0.1949385473316766,
 0.2228132312904445,
 0.19079333814234423,
 0.24532159312176316,
 0.2596521194186951,
 0.20530524020503654,
 0.2303592470273772,
 0.1750192985537002,
 0.2609628974903337,
 0.2598801341212257,
 0.2610

In [148]:
import numpy as np

list1 = [1, 2, 3]
list2 = [4, 5, 6]
list3 = [7, 8, 9]

ndarray_name = np.empty((0, len(list1)), int) # 빈 2차원 ndarray 생성

for lst in [list1, list2, list3]:
    ndarray_name = np.vstack([ndarray_name, np.array(lst)]) # 리스트를 2차원 ndarray로 변환하여, 이전 ndarray에 추가

print(ndarray_name)


[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [149]:
type(ndarray_name)

numpy.ndarray

In [150]:
type(ndarray_name[0])

numpy.ndarray